version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands: 
        - 'echo "--------INSTALL PHASE--------"'
        - 'npm install -g aws-cdk'
        - 'python --version'
        - 'pip install -r requirements.txt'
  build:
    commands:
        - 'echo "--------BUILD PHASE--------"'
        - "cdk synth '*' "
artifacts:
    base-directory: cdk.out
    files: 
        - '**/*'